### ISSUE TITLE
Широтно-импульсная модуляция

### ISSUE THREAD

**Issue by netnazgul** [Michail-Petrushko/Work_NT-Lab#11]
https://github.com/Michail-Petrushko/Work_NT-Lab/blob/0125deecd1c3086d803b426d3746f2933e782a5b/HSV-RGB/HSV-RGB.srcs/sources_1/new/PWM.v#L46
По сути есть два параметра - период импульса T и скважность импульса D. Период у тебя константа и определяется размерностью счётчика, сейчас 8 бит т.е. 256 отсчётов. Скважность же зависит от входа и его размерности, сейчас тоже наверное 8 бит и тоже 256 отсчётов. 
Т.е. можно либо увеличивать размер счётчика (при 9 битах уже будет максимум 50% например), либо уменьшать размеры входных сигналов. Это в одну сторону влияет на количество используемых триггеров, в другую - на разрешение управляющего сигнала.

Также можно сбрасывать счётчик до достижения максимального значения и получать таким образом другие требуемые соотношения. Например, если вход имеет значения от 0 до 99, счётчик можно выполнить как счёт от 0 до 199, получив таким образом максимальную скважность импульса 50% с шагом 0.5% (1/200).

**Comment by Michail-Petrushko** [comment]
изменил на 9 битов
