### ISSUE TITLE
Функционал sw[1]

### ISSUE THREAD

**Issue by netnazgul** [Michail-Petrushko/Work_NT-Lab#13]
https://github.com/Michail-Petrushko/Work_NT-Lab/blob/430e25e7cdcc3d8ddd51bc721bae1971e0fbc7ae/HSV-RGB/HSV-RGB.srcs/sources_1/new/BTNs_test.v#L37-L53
Что должно выполняться по сигналам `sw[0]` и `sw[1]`?

При `sw[1] == 1` и `sw[0] == 1` на каждом такте будет выполняться сначала первое условие, потом второе.

Аналогично для `sw[1] == 1` и последующих блоков `always`.

Если это синхронный сброс, то подобная ветка должна быть исключительной.

**Comment by Michail-Petrushko** [comment]
исправил.  sw[1] был использован временно, чтобы отследить в каком блоке проблема с reset
