### ISSUE TITLE
Обработка счётчика counter1

### ISSUE THREAD

**Issue by netnazgul** [Michail-Petrushko/Work_NT-Lab#14]
https://github.com/Michail-Petrushko/Work_NT-Lab/blob/430e25e7cdcc3d8ddd51bc721bae1971e0fbc7ae/HSV-RGB/HSV-RGB.srcs/sources_1/new/BTNs_test.v#L44-L51
Проверка значения счётчика в таком описании для самого счётчика бессмысленна - он всё равно будет считать полную разрядность от 0 до 2^20-1.

**Comment by Michail-Petrushko** [comment]
counter1 = counter1+1; 
 if (counter1 == 0) begin  
     h = h+1; 
     if (h>359) h = h - 360; 
     if (h<0) h = h+360; 
     Hue = h; 
     counter1 = 0; 
 end 


Такую конструкцию я использовал специально, чтобы замедлить увеличение значения Hue

**Comment by netnazgul** [comment]
Да, это понятно. Вопрос тут был в строке `counter1 = 0` - в таком описании она избыточна, т.к. мы в `if` и так уже проверили, что счётчик равен нулю.

**Comment by Michail-Petrushko** [comment]
Согласен)))
