### ISSUE TITLE
Корректность проверки счётчиков в BTNs_test

### ISSUE THREAD

**Issue by netnazgul** [Michail-Petrushko/Work_NT-Lab#17]
https://github.com/Michail-Petrushko/Work_NT-Lab/blob/ccb6f2a2d6eef89e7cdb3341cc1037d5ec63d59b/HSV-RGB/HSV-RGB.srcs/sources_1/new/BTNs_test.v#L67-L69
При таком вычислении счётчику придётся прокрутиться и переполниться несколько раз, прежде чем его значение станет равно нулю, т.к. счётчик двоичный, а прибавляем не степень двойки.

Как пример - если бы мы прибавляли 5 к четырёхразрядному счётчику:
```
код   значение
0000    0
0101    5
1010    10
1111    15
0100    4    * переполнение
1001    9
1110    14
0011    3    * переполнение
1000    8
1101    13
0010    2    * переполнение
...
```

**Comment by Michail-Petrushko** [comment]
Я так и хотел ;) Хотя в принципе можно просто увеличить разрядность counter3 на 1

**Comment by netnazgul** [comment]
> Хотя в принципе можно просто увеличить разрядность counter3 на 1

Вопрос не в разрядности, а в некорректном описании алгоритма. Совершенно не понимаю логику задания многоразрядного счётчика, которому нужно несколько раз прокрутиться через переполнение, прежде чем он достигнет проверяемого значения. Такую конструкцию неудобно читать и неудобно изменять. 
Простой вопрос - какое количество тактов требуется для достижения условия `counter3 == 0`?
