### ISSUE TITLE
Debouncer входов с реле и кнопок

### ISSUE THREAD

**Issue by netnazgul** [Michail-Petrushko/Work_NT-Lab#3]
https://github.com/Michail-Petrushko/Work_NT-Lab/blob/0125deecd1c3086d803b426d3746f2933e782a5b/HSV-RGB/HSV-RGB.srcs/sources_1/new/BTNs_test.v#L37-L39
Есть ли debouncer-схема для входов с кнопок? При её отсутствии сигнал от кнопки может иметь глитчи, и `posedge` сработает несколько раз при однократном нажатии.
`sost` не используется нигде в коде, присваивается как число, однако описывается как 1 бит.

**Comment by netnazgul** [comment]
https://github.com/Michail-Petrushko/Work_NT-Lab/blob/0125deecd1c3086d803b426d3746f2933e782a5b/HSV-RGB/HSV-RGB.srcs/sources_1/new/BTNs_test.v#L48

**Comment by Michail-Petrushko** [comment]
+
