### ISSUE TITLE
Описание режимов работы системы

### ISSUE THREAD

**Issue by netnazgul** [Michail-Petrushko/Work_NT-Lab#6]
https://github.com/Michail-Petrushko/Work_NT-Lab/blob/0125deecd1c3086d803b426d3746f2933e782a5b/HSV-RGB/HSV-RGB.srcs/sources_1/new/BTNs_test.v#L70-L82
Исходя из этой логики, `S` и `V` всегда константа?
Для программирования режимов необходимо описать конечный автомат (state machine), состояние которого переключается по синхросигналу в зависимости от нажатий кнопок, а логика изменения выходов зависит от данного состояния.

**Comment by Michail-Petrushko** [comment]
блоки переделаны
